pub struct Build {
    pub id:          u64,
    pub repo_id:     u64,
    pub status:      String,
    pub Error:       String,
    pub enqueued_at: NaiveDateTime,
    pub created_at:  NaiveDateTime,
    pub started_at:  NaiveDateTime,
    pub finished_at: NaiveDateTime,
    pub commit:      String,
    pub branch:      String,
    pub _ref:        String,
    pub title:       String,
    pub message:     String,
    pub timestamp:   u64,
    pub sender:      String,
    pub author:      String,
    pub avatar:      String,
    pub email:       String,
    pub url:         String,
    pub signed:      bool,
    pub Verified:    bool,
}
